spring.application.name=secureauth
#spring.application.name=auth

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# for debugging
logging.level.org.springframework.security=DEBUG 
#limits cookies things from another wb req
server.servlet.session.cookie.same-site=lax
#SameSite=Lax limits cross-site cookie sending while still supporting common login navigation. Spring Boot exposes these cookie settings directly.

# Cookie security
server.servlet.session.cookie.http-only=true

#mailer
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties[mail.smtp.auth]=true
spring.mail.properties[mail.smtp.starttls.enable]=true

spring.mail.properties[mail.smtp.connectiontimeout]=5000
spring.mail.properties[mail.smtp.timeout]=3000
spring.mail.properties[mail.smtp.writetimeout]=5000

app.mail.from=${MAIL_FROM}

app.auth.verify-email-url=http://localhost:8080/api/auth/verify-email