spring.application.name=secureauth
#spring.application.name=auth

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# for debugging
logging.level.org.springframework.security=DEBUG 
#limits cookies things from another wb req
server.servlet.session.cookie.same-site=lax
#SameSite=Lax limits cross-site cookie sending while still supporting common login navigation. Spring Boot exposes these cookie settings directly.

# Cookie security
server.servlet.session.cookie.http-only=true
